### ISSUE TITLE
Storybook is not working while using storybook-design-token in IE11 and Edge browsers.

### ISSUE THREAD

**Issue by qburst-akhilp** [UX-and-I/storybook-design-token#29] opened 2020-09-14 12:19 UTC
I have used `storybook-design-token` in our react storybook design system. It's working fine in all browsers except IE11 and Edge. Are you giving support for this addon in IE11 and Edge? 
<img width="950" alt="Screenshot 2020-09-11 at 11 13 29 AM" src="https://user-images.githubusercontent.com/48544881/93084382-92289980-f6b1-11ea-8cdd-400fa4faf3fc.png">

**Comment by Sqrrl** [comment] 2020-09-14 12:46
Hey. Looks like a regression. It once worked, see https://github.com/UX-and-I/storybook-design-token/issues/8.

Will look into this as soon as possible.

**Comment by Sqrrl** [comment] 2020-09-25 10:55
Think I found the issue. Could you please verify using v0.7.9?

**Comment by Sqrrl** [comment] 2020-10-12 13:38
Closing. Feel free to re-open if your issue is not fixed.

**Closed by Sqrrl** 2020-10-12 13:38 UTC
Labels: bug
